### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/slimemold-service#12]
Create a docker image for the API to make it usable by myxo and other projects interacting with circles

**Comment by JacqueGM** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/slimemold-service/12?planning-poker) with Zenhub @llunaCreixent
