### ISSUE TITLE
Define TypeScript types for API request and response bodies

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/slimemold-service#17]
- Create definition
- Test definitions

**Comment by llunaCreixent** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/slimemold-service/17?planning-poker) with Zenhub @JacqueGM @llunaCreixent
