### ISSUE TITLE
Review slimemold service to fit scope for  pathfinder2 integration

### ISSUE THREAD

**Issue by JacqueGM** [CirclesUBI/slimemold-service#21]
- check what is missing to do the integratin
- what needs to be updated 
- what needs to be deleted

**Comment by JacqueGM** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/slimemold-service/21?planning-poker) with Zenhub @llunaCreixent

**Comment by llunaCreixent** [comment]
Not relevant anymore :)
