### ISSUE TITLE
Implement findTransferSteps function calling the pathfinder2 service

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/slimemold-service#22]
Enable this endpoint to use any of the parameters from the definition of the pathfinder2  https://hackmd.io/Gg04t7gjQKeDW2Q6Jchp0Q
- Create test cases 
-  Test with production data

**Comment by JacqueGM** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/slimemold-service/22?planning-poker) with Zenhub @llunaCreixent

**Comment by llunaCreixent** [comment]
Done in circles-core
