### ISSUE TITLE
Review the  API proxy concept

### ISSUE THREAD

**Issue by JacqueGM** [CirclesUBI/slimemold-service#25]
- review the concept of API Proxy
- review how an API can collect the number of request and comunicate this to the backend service

**Comment by llunaCreixent** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/slimemold-service/25?planning-poker) with Zenhub @JacqueGM @llunaCreixent

**Comment by JacqueGM** [comment]
Here a version written by @jaensen https://github.com/CirclesUBI/pathfinder-proxy
