### ISSUE TITLE
Define public HTTP API

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/slimemold-service#6]
What we have had so far: https://github.com/CirclesUBI/circles-api/blob/main/API.md#find-transitive-transfer-steps

**What we need**

- [ ] Find transitive transfer steps

**Nice to have**

- [ ] Get trust connections of a node

**Comment by JacqueGM** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/slimemold-service/6?planning-poker) with Zenhub @llunaCreixent
